[package]
name = "gapless"
version = "0.1.0"
authors = []

[dependencies]
amethyst = { path = "src/amethyst" }
# amethyst = {git = "https://github.com/amethyst/amethyst", features = ["nightly"]}
serde_derive = "1.0"
serde = "1.0"

